name: "Setup dependencies"
description: "Install dependencies"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "24.x"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # version 6.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Node.js dependencies
      run: npm install